### Transforming the code  into idiomatic Python
-  Replace traditional index manupulation with python core looping idiomatic

In [1]:
# Looping over a range of numbers - Traditional approach
for i in[0,1,2,3,4,5]:
    print(i**2,end = " ")

0 1 4 9 16 25 

In [2]:
#Idiomatic programming
for i in range(6):
    print(i**2,end = " ")

0 1 4 9 16 25 

### Looping  over a collection

In [3]:
colors = ['red','green','black','blue']
for i in range(len(colors)):
    print(colors[i],end = " ")

red green black blue 

In [5]:
for color in colors:  # idiomatic program of previous program
    print(color,end = ' ')

red green black blue 

### Looping backwards

In [6]:
colors = ['red','green','blue','black']
for i in range(len(colors)-1,-1,-1):
    print(colors[i], end = ' ')

black blue green red 

In [7]:
for color in reversed (colors):
    print(color,end = ' ')

black blue green red 

In [9]:
colors = ['red','green','blue','black']
for color in sorted(colors):
    print(color,end = ' ')

black blue green red 

In [10]:
colors = ['red','green','blue','black']
for color in sorted(colors,reverse = True):
    print(color,end = ' ')

red green blue black 

### 
- if x<= y and y<= z :
-  if x<=y<=z:
-  if x == true
-  if x:


### Pandas approach

In [12]:
import pandas as pd


In [15]:
dt =  {'id':[11,12,13,14,15],
      'first name' :['A','B','C','D','E'],
        'company' : ['aa','bb','cc','dd','ee'],
        'address': ['Hyd','Hyd','Hyd','Hyd','Hyd']}
mydt = pd.DataFrame(dt)

In [16]:
print(mydt)

   id first name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [ ]:
import os


In [ ]:
os.chdir('Pathfile') #saves to certain location

In [17]:
mydt.to_csv('workingFile.csv',index = False)

### Reading the data from csv file

In [21]:
mydata = pd.read_csv('workingFile.csv')

In [22]:
print(mydata)

   id first name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [23]:
mydata1 = pd.read_csv('workingFile.csv',names = ["custId","Name","Company","Address"])

In [24]:
print(mydata1)

  custId        Name  Company  Address
0     id  first name  company  address
1     11           A       aa      Hyd
2     12           B       bb      Hyd
3     13           C       cc      Hyd
4     14           D       dd      Hyd
5     15           E       ee      Hyd


In [27]:
mydata1 = pd.read_csv('workingFile.csv',skiprows=[1,2,3],names = ["custId","Name","Company","Address"])

In [28]:
print(mydata1)

  custId        Name  Company  Address
0     id  first name  company  address
1     14           D       dd      Hyd
2     15           E       ee      Hyd


In [29]:
pwd

'C:\\Users\\219'

### print only two columns
### Print the large value from custId column
### Print the least value in custId column
### Average of CustId --sum(li)/len(li)

### Numpy - Working with Multi Dimensional array
- numpy array is a bit like python list
- Numpy array is data stucture of numpy lib
- it's shortname for Numeric Python

In [43]:
import numpy as np

In [44]:
li = [1,2,3,4,5]
print(li,end= " ")

[1, 2, 3, 4, 5] 

In [45]:
array = np.array(li)
print(array)

[1 2 3 4 5]


In [47]:
a1 = np.array ([(1,2,3),(4,5,6,)])
print (a1.shape)

(2, 3)


In [53]:
a1 = np.array ([(1,2,3),(4,5,6,)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
a1 = np.array([(1,2,3)])
a2 = np.array([(4,5,6)])
print(np.hstack((a1,a2)))

[[1 2 3 4 5 6]]


In [59]:
a1 = np.array([(1,2,3)])
a2 = np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]
